SRCDIRS=src
SRCS=$(foreach dir,$(SRCDIRS),$(wildcard $(dir)/*.cpp))
PROGDIR=build
PROGRAM=CCV.exe
RESDIR = res
WXCONFIG = $(RESDIR)/win/wx-config.exe
DLLDIR = $(RESDIR)/win/dll
DOCDIR = docs
DOXYGEN = doxygen
DOXYCONFIG = $(RESDIR)/Doxyfile

all: $(PROGRAM) html
     
clean:
	rm -fr $(PROGDIR) *.app
	
html:
	mkdir -p $(DOCDIR)
	$(DOXYGEN) $(DOXYCONFIG)

$(PROGRAM):
	mkdir -p build
	g++ -m32 $(SRCS) `$(WXCONFIG) --libs --cxxflags` -o $(PROGDIR)/$(PROGRAM)
	cp $(DLLDIR)/*.dll $(PROGDIR)
